# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestandoTableview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestandoTableview
   #pod 'JASON', '~> 3.0'
   pod 'RxSwift','~> 4.5.0' #reatividade
   pod 'RxCocoa','~> 4.5.0'
   pod 'RxRealm','~> 0.7.6'
   pod 'Realm','~> 3.20.0'
   pod 'RealmSwift','~> 3.20.0'
   pod 'SwiftyJSON','~> 4.0' # trabalhar com json parser,campos vazioe evitar quebras
   pod 'LabelConfigurator','~> 0.3.0' # trando do texto label desccricao
  # pod 'PaginatedTableView' # paginacao infinita
   pod 'Alamofire','~> 5.0' #rede facil
   pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
   
   target 'TestandoTableviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestandoTableviewUITests' do
    # Pods for testing
  end

end
